apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: pubg-leaderboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator

