apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pubg-leaderboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gbasileGP/foe-local-k8s'
    path: pubg-leaderboard
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pubg-leaderboard
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
