apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: redis-cluster
spec:
  project: default
  source:
    repoURL: 'https://github.com/gbasileGP/foe-local-k8s.git'
    targetRevision: HEAD
    path: redis-cluster
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

